spring:
    application:
        name: eureka-server
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/dabaicaiSearch?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    typeAliasesPackage: com.dabaicai.search.api.mapper
    mapperLocations: classpath:mapper/*.xml



server:
    port: 7000

eureka:
    instance:
        hostname: localhost
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



